name: CI/CD pipeline for backend development
on:
  push:
    branches:
      - development

  pull_request:
    branches:
      - development
      
jobs:
  build: 
    runs-on: ${{matrix.os}}
    strategy: 
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04, macos-latest, macos-13]
        
    services:
      postgres:
        image: postgres:14
        env: 
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: study_platform_db
          
        ports: 
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env: 
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/study_platform_db 
      FLASK_APP: app

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        
      - name: Set up Docker for Linux
        if: runner.os == 'ubuntu'
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          
      - name: Install Docker on macOS
        if: runner.os == 'macos'
        run: |
          brew install --cask docker
          open -g -a Docker
          # Wait for Docker to start up (optional)
          while ! docker info > /dev/null 2>&1; do
            echo "Waiting for Docker to start..."
            sleep 5
          done
          
      - name:  setup python
        uses: actions/setup-python@v3
        with: 
          python-version: '3.12.x'

      - name: upgrade pip
        run: 
          python -m pip install --upgrade pip
          
      - name: install dependecies
        run:
          pip install -r requirements.txt
          
      - name: load .env file
        run:
          cat ./server/.env >> $GITHUB_ENV
          
      - name: run migrations
        working-directory: ./server
        env:
          DATABASE_URL: ${{env.DATABASE_URL}}
        run:
          flask db upgrade head
          
          
        
      
    
