name: CI/CD pipeline for backend development
on:
  push:
    branches:
      - development

  pull_request:
    branches:
      - development
      
jobs:
  build: 
    runs-on: ${{matrix.os}}
    strategy: 
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04, macos-latest, macos-13]
        
    services:
      postgres:
        image: postgres:14
        env: 
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: study_platform_db
        ports: 
          - 5432:5432
    env: 
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/study_platform_db 
      FLASK_APP: app

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name:  setup python
        uses: actions/setup-python@v3
        with: 
          python-version: '3.12.x'

      - name: upgrade pip
        run: 
          python -m pip install --upgrade pip
          
      - name: install dependecies
        run:
          pip install -r requirements.txt
          
      - name: load .env file
        run:
          cat ./server/.env >> $GITHUB_ENV
          
      - name: run migrations
        working-directory: ./server
        env:
          DATABASE_URL: ${{env.DATABASE_URL}}
        run:
          flask db upgrade head
          
          
        
      
    
